# Generated by Django 4.1.7 on 2023-03-30 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leagueprobs',
            name='total_games',
            field=models.IntegerField(default=38),
        ),
    ]
