# Generated by Django 4.1.7 on 2023-04-06 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0002_leagueprobs_total_games'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leagueprobs',
            name='total_games',
            field=models.PositiveIntegerField(default=38),
        ),
        migrations.AlterField(
            model_name='leaguerow',
            name='draws',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='leaguerow',
            name='losses',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='leaguerow',
            name='wins',
            field=models.PositiveIntegerField(),
        ),
    ]
