# Generated by Django 4.1.7 on 2023-04-06 18:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0003_alter_leagueprobs_total_games_alter_leaguerow_draws_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaguerow',
            name='draws',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='leaguerow',
            name='losses',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='leaguerow',
            name='probab',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='leaguerow',
            name='wins',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
